language: python
env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda update -q conda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - conda create -n test-environment python=$PYTHON_VERSION
  - conda activate test-environment
  - conda install -q --file conda_requirements.txt
  - pip install --upgrade -r pip_requirements.txt
  - pip install coveralls

script:
  - coverage run --source=iembot setup.py test

after_success:
  - coveralls
